apiVersion: v1
entries:
  ocd-builder:
  - created: 2018-12-25T15:24:54.349398Z
    description: Builder of application images
    digest: 689f9f38ada2c5ef398fd1ba4b1920f918afb0f0efdab904a3376fc0a7cfe2b3
    home: https://github.com/ocd-scm/ocd-builder
    keywords:
    - builder
    - openshift
    name: ocd-builder
    sources:
    - https://github.com/ocd-scm/ocd-builder
    urls:
    - https://ocd-scm.github.io/ocd-meta/charts/ocd-builder-1.0.0.tgz
    version: 1.0.0
  ocd-builder-credentials:
  - created: 2018-12-25T15:24:54.349953Z
    description: Creates secrets that can be upgraded and rolled back
    digest: 5fb7aa4001f5af97ab0d1e376fe90b2c67927152a5236ddd7980e056bbe16de8
    home: https://github.com/ocd-scm/ocd-builder-credentials
    keywords:
    - ocd
    - ocd-builder
    - credentials
    name: ocd-builder-credentials
    sources:
    - https://github.com/ocd-scm/ocd-builder-credentials
    urls:
    - https://ocd-scm.github.io/ocd-meta/charts/ocd-builder-credentials-1.0.0.tgz
    version: 1.0.0
  ocd-builder-webhook:
  - created: 2018-12-25T15:24:54.350658Z
    description: A webhook that triggers ocd-builder
    digest: d90d18fd687368ec389706ae92f4296df4df575ea0f41a8f3ec91e7057788b3a
    home: https://github.com/ocd-scm/ocd-builder-webhook
    keywords:
    - ocd-builder-webhook
    - ocd-scm
    - openshift
    name: ocd-builder-webhook
    sources:
    - https://github.com/ocd-scm/ocd-builder-webhook
    urls:
    - https://ocd-scm.github.io/ocd-meta/charts/ocd-builder-webhook-1.0.0.tgz
    version: 1.0.0
  ocd-secret:
  - created: 2018-12-25T15:24:54.351257Z
    description: Creates secrets that can be upgraded and rolled back
    digest: 625ad5b5f85a5aa31a5db832aabb581f8be34ba35326ca992d579f70de24253d
    home: https://github.com/ocd-scm/ocd-secret.git
    keywords:
    - ocd
    - secret
    name: ocd-secret
    sources:
    - https://github.com/ocd-scm/ocd-secret.git
    urls:
    - https://ocd-scm.github.io/ocd-meta/charts/ocd-secret-1.0.0.tgz
    version: 1.0.0
generated: 2018-12-25T15:24:54.346276Z
